---
driver:
  name: docker
  use_sudo: false
#  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
#  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
